{
 "title": "Root Endpoint Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Swagger UI Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_server_requests_seconds_count{uri=\"/swagger-ui*/**\", job=\"kanban-service\", method=\"GET\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Swagger UI total calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by(job) (http_server_requests_seconds_count{uri=\"/swagger-ui*/**\", job=\"kanban-service\", method=\"GET\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Endpoint Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(job) (rate(http_server_requests_seconds_count{uri=\"/\", method=\"GET\", job=\"kanban-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Root Endpoint Calls",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by(job) (http_server_requests_seconds_count{job=\"kanban-service\", uri=\"/\", method=\"GET\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}